icons_format = "{icon}"

[theme]
theme = "nord-dark"

[icons]
icons = "awesome4"

[icons.overrides]
bat = ["", "", "", "", ""]
bat_charging = ""

[[block]]
block = "cpu"
interval = 1
format = "  $utilization  "

[[block]]
block = "disk_space"
path = "/"
interval = 20
format = "  $available.eng(w:2) "

[[block]]
block = "memory"
interval = 5
format = "  $mem_total_used_percents  "
format_alt = "  $swap_used_percents "
[[block]]
block = "net"
format = " $icon  {$signal_strength $ssid $ip [$speed_up]}"
[block.theme_overrides]
idle_bg = "#ebcb8b"
idle_fg = "#2e3440"

[[block]]
block = "sound"
driver = "pulseaudio"
max_vol = 150
step_width = 3
[block.theme_overrides]
idle_bg = "#7aa2f7"
idle_fg = "#2e3440"

[[block]]
block = "backlight"
device = "amdgpu_bl1"
step_width = 5

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:' %a,%d-%m-%Y |  %H:%M:%S') "
